FROM alpine:latest

RUN apk upgrade --update && apk add --no-cache \
    php83 \
    php83-session \
    php83-pdo \
    php83-pdo_pgsql \
    php83-pgsql \
    php83-json \
    php83-mbstring \
    wget

# Télécharger Adminer
RUN mkdir -p /var/www/html && \
    wget -O /var/www/html/index.php https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php

WORKDIR /var/www/html

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080"]