services:
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    volumes:
      - vendor:/app/vendor
    working_dir: /app
  symfony:
    build:
      context: .
      dockerfile: Dockerfile.symfony
    volumes:
      - vendor:/app
    ports:
      - "8001:8000"
    depends_on:
      - composer

volumes:
  vendor:
